[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "updated_docs"
authors = [{name = "Mark Harvey", email = "inspiredharvey@gmail.com"}]
readme = "README.md"
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]
dynamic = ["version", "description"]
requires = []
requires-python=">=3.10"
description-file="README.md"

[project.urls]
Home = "https://github.com/harvey251/updated-docs"

[tool.semantic_release]
version_variable = "updated_docs/__init__.py:__version__"

[tool.black]
line-length = 120