[tool.poetry]
name = "goa"
version = "0.1.0"
description = "goa (Global Optimization Animations) helps visualize the execution of some global optimization algorithms on a given problem."
authors = ["Lorenzo Palloni"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
matplotlib = "^3.4.3"
numpy = "^1.21.2"
imageio = "^2.9.0"
imageio-ffmpeg = "^0.4.5"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
