[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "django-soap"
version = "0.1.6"
description = ""
authors = ["Your Name <you@example.com>"]
license = "BSD"

[tool.poetry.dependencies]
python = "^3.7"
Django = "^2.2"
requests = "^2.26.0"
xmltodict = "^0.12.0"

[tool.poetry.dev-dependencies]
